### ISSUE TITLE
Can this package be used in ros2?

### ISSUE THREAD

**Issue by miku54** [methylDragon/ros-sensor-fusion-tutorial#7]
Is the functionality implemented by this package consistent with that of robot_pose_ekf?

**Comment by methylDragon** [comment]
Hi there!

I'm not too aware of a `robot_pose_ekf` for ROS2. But as far as I know, `robot_localization` is better than the ROS1 `robot_pose_ekf` because it allows for the fusion of any arbitrary number of odometry sources, as well as more granularity in setting the covariance matrices. [See more](https://github.com/correll/advancedrobotics/issues/44)

Furthermore, `robot_pose_ekf` is in an unmaintained state..

As for usability with ROS2... `robot_localization` is a ROS1 package, but you might be able to still use `robot_localization` by using the [ros1_bridge](https://github.com/ros2/ros1_bridge), as long as you ensure that the odometry messages are appropriately translated.

I unfortunately have not yet explored ROS2 options for sensor fusion.

**Comment by miku54** [comment]
Hey bro, it works!
I'll give you feedback when I debug my car.

methylDragon ***@***.***> 于2021年3月30日周二 下午3:32写道：

**Comment by KingBoomie** [comment]
`robot_localization` supports ros2. just look in the foxy or galactic branches in the repo. 

One of the creators of `robot_localization` is working on a ROS2 native sensor fusion package [fuse](https://github.com/locusrobotics/fuse), but it's very experimental, continuously updated, and the docs seems to be pretty out of date.
